# Generated by Django 3.0 on 2021-01-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_db_apis_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_apis',
            name='body_method',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='body_method',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
